<a href="https://colab.research.google.com/github/brunobertin-byte/TEC.PROGRAMA-O-FATEC/blob/main/Aula_2_tec_prog_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ==============================================================================
# NOTEBOOK 02: LIVE CODING PARCIAL & REFATORAÇÃO
# Curso: Ciência de Dados - Fatec
# Disciplina: Técnicas de Programação
# Autor: Bruno Bertin Vitorino
# Data: 17/08/2026
# ==============================================================================

In [2]:
import pandas as pd

In [3]:
# ------------------------------------------------------------------------------
# CÓDIGO INICIAL (CÓDIGO REPETITIVO / "RUIM")
# Observe como o mesmo pipeline de tratamento é repetido 3 vezes.
# ------------------------------------------------------------------------------

# Processamento do Dataset 1
df1 = pd.read_csv("https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv")
# Exemplo simulado de limpeza repetitiva:
df1_clean = df1.drop(columns=["Code"], errors='ignore')
df1_clean = df1_clean.rename(columns={"Value": "Valor"})

# Processamento do Dataset 2 (Copiar e colar idêntico)
df2 = pd.read_csv("https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv")
df2_clean = df2.drop(columns=["Code"], errors='ignore')
df2_clean = df2_clean.rename(columns={"Value": "Valor"})

display(df1_clean.head())
display(df2_clean.head())

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

# 🎯 DESAFIO DE REFATORAÇÃO (PASSO A PASSO)

## PASSO 1: Complete a função abaixo para unificar o tratamento

In [4]:
def carregar_e_limpar(url_ou_caminho, coluna_drop):
    """
    Função genérica para carregar e limpar datasets de indicadores.
    """
    # 1. Leia o CSV usando pandas
    df = pd.read_csv(url_ou_caminho)

    # 2. Remova a coluna passada no parâmetro
    df = df.drop(columns=[coluna_drop], errors='ignore')

    # 3. Renomeie a coluna 'Value' para 'Valor'
    df = df.rename(columns={"Value": "Valor"})

    # 4. Retorne o dataframe limpo
    return df

## PASSO 2: Teste sua função chamando-a para 2 arquivos diferentes em uma linha cada

In [5]:
gdp_url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"

# Teste com o primeiro dataset
df1_ok = carregar_e_limpar(gdp_url, "Code")
display(df1_ok.head())

# Teste com o segundo dataset (mesma URL para demonstração de reuso)
df2_ok = carregar_e_limpar(gdp_url, "Code")
display(df2_ok.head())

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Agrupar por ano e somar os valores para visualizar a tendência geral
df_yearly_sum = df1_ok.groupby('Year')['Valor'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Year', y='Valor', data=df_yearly_sum)
plt.title('Soma Total do Valor por Ano')
plt.xlabel('Ano')
plt.ylabel('Soma Total do Valor')
plt.grid(True)
plt.show()

In [6]:
# Calcular a correlação entre 'Valor' e 'Ano'
correlation = df1_ok['Valor'].corr(df1_ok['Year'])

print(f"A correlação entre Valor e Ano é: {correlation:.4f}")

A correlação entre Valor e Ano é: 0.1674

In [7]:
gdp_url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"

# Chamando a função para processar o equivalente a df1
df1_processado_pela_funcao = carregar_e_limpar(gdp_url, "Code")
print("DF1 processado pela função:")
display(df1_processado_pela_funcao.head())

# Chamando a função para processar o equivalente a df2
df2_processado_pela_funcao = carregar_e_limpar(gdp_url, "Code")
print("\nDF2 processado pela função:")
display(df2_processado_pela_funcao.head())

DF1 processado pela função:

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

DF2 processado pela função:

  Country Name Country Code  Year         Valor
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09